apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-web-app
  template:
    metadata:
      labels:
        app: cloud-web-app
    spec:
      containers:
      - name: cloud-web-app
        image: mydevopsacr.azurecr.io/cloud-web-app:1.0
        ports:
        - containerPort: 5000
